[package]
name = "bus_server"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
geo = "0.29.3"
sqlite = "0.36.1"
#serde = "1.0.216"

#[dependencies.mongodb]
#version = "3.1.1"
#features = ["sync"]